// Comprehensive PDF translations for all document types
// This file contains all labels used in PDF generation

export const PDF_TRANSLATIONS = {
  en: {
    // Document types
    invoice: "INVOICE",
    receipt: "RECEIPT",
    vatReport: "VAT REPORT",
    expenseReport: "EXPENSE REPORT",
    contract: "EMPLOYEE CONTRACT",
    
    // Common labels
    issueDate: "Issue Date",
    dueDate: "Due Date",
    invoiceNumber: "Invoice #",
    receiptNumber: "Receipt #",
    saleNumber: "Sale #",
    from: "From",
    to: "To",
    billTo: "Bill To",
    
    // Company/Customer info
    companyName: "Company Name",
    customerName: "Customer Name",
    customerEmail: "Email",
    customerPhone: "Phone",
    supplierTRN: "Supplier TRN",
    customerTRN: "Customer TRN",
    address: "Address",
    phone: "Phone",
    email: "Email",
    trn: "TRN",
    
    // Table headers
    description: "Description",
    item: "Item",
    quantity: "Qty",
    unitPrice: "Unit Price",
    price: "Price",
    discount: "Discount",
    vat: "VAT (5%)",
    vatRate: "VAT Rate",
    lineTotal: "Total",
    amount: "Amount",
    
    // Totals
    subtotal: "Subtotal",
    totalDiscount: "Total Discount",
    vatAmount: "VAT Amount",
    total: "Total Amount",
    grandTotal: "Grand Total",
    
    // Payment
    paymentTerms: "Payment Terms",
    paymentMethod: "Payment Method",
    paymentDate: "Payment Date",
    paidAmount: "Paid Amount",
    outstanding: "Outstanding",
    
    // Other
    notes: "Notes",
    thankYou: "Thank you for your business!",
    generatedBy: "Generated by",
    
    // VAT Report specific
    period: "Period",
    taxableSales: "Taxable Sales",
    vatCollected: "VAT Collected",
    vatPaid: "VAT Paid",
    netVatPayable: "Net VAT Payable",
    totalInvoices: "Total Invoices",
    
    // Expense Report specific
    category: "Category",
    date: "Date",
    supplier: "Supplier",
    paymentType: "Payment Type",
    vatApplicable: "VAT Applicable",
    baseAmount: "Base Amount",
    totalExpenses: "Total Expenses",
    
    // HR/Contract specific
    employee: "Employee",
    employeeName: "Employee Name",
    designation: "Designation",
    contractType: "Contract Type",
    startDate: "Start Date",
    endDate: "End Date",
    basicSalary: "Basic Salary",
    allowance: "Allowance",
    totalSalary: "Total Salary",
    terms: "Terms and Conditions",
    
    // Status
    status: "Status",
    draft: "Draft",
    sent: "Sent",
    paid: "Paid",
    overdue: "Overdue",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected"
  },
  ar: {
    // Document types
    invoice: "فاتورة",
    receipt: "إيصال",
    vatReport: "تقرير ضريبة القيمة المضافة",
    expenseReport: "تقرير المصروفات",
    contract: "عقد موظف",
    
    // Common labels
    issueDate: "تاريخ الإصدار",
    dueDate: "تاريخ الاستحقاق",
    invoiceNumber: "رقم الفاتورة",
    receiptNumber: "رقم الإيصال",
    saleNumber: "رقم البيع",
    from: "من",
    to: "إلى",
    billTo: "بيانات العميل",
    
    // Company/Customer info
    companyName: "اسم الشركة",
    customerName: "اسم العميل",
    customerEmail: "البريد الإلكتروني",
    customerPhone: "رقم الهاتف",
    supplierTRN: "رقم تسجيل المورد",
    customerTRN: "رقم تسجيل العميل",
    address: "العنوان",
    phone: "الهاتف",
    email: "البريد الإلكتروني",
    trn: "الرقم الضريبي",
    
    // Table headers
    description: "الوصف",
    item: "الصنف",
    quantity: "الكمية",
    unitPrice: "سعر الوحدة",
    price: "السعر",
    discount: "الخصم",
    vat: "ضريبة القيمة المضافة (٪5)",
    vatRate: "معدل الضريبة",
    lineTotal: "المجموع",
    amount: "المبلغ",
    
    // Totals
    subtotal: "المجموع الفرعي",
    totalDiscount: "إجمالي الخصم",
    vatAmount: "مبلغ ضريبة القيمة المضافة",
    total: "الإجمالي",
    grandTotal: "الإجمالي الكلي",
    
    // Payment
    paymentTerms: "شروط الدفع",
    paymentMethod: "طريقة الدفع",
    paymentDate: "تاريخ الدفع",
    paidAmount: "المبلغ المدفوع",
    outstanding: "المتبقي",
    
    // Other
    notes: "ملاحظات",
    thankYou: "شكراً لتعاملك معنا!",
    generatedBy: "تم إنشاؤه بواسطة",
    
    // VAT Report specific
    period: "الفترة",
    taxableSales: "المبيعات الخاضعة للضريبة",
    vatCollected: "ضريبة القيمة المضافة المحصلة",
    vatPaid: "ضريبة القيمة المضافة المدفوعة",
    netVatPayable: "صافي ضريبة القيمة المضافة المستحقة",
    totalInvoices: "إجمالي الفواتير",
    
    // Expense Report specific
    category: "الفئة",
    date: "التاريخ",
    supplier: "المورد",
    paymentType: "نوع الدفع",
    vatApplicable: "ضريبة القيمة المضافة قابلة للتطبيق",
    baseAmount: "المبلغ الأساسي",
    totalExpenses: "إجمالي المصروفات",
    
    // HR/Contract specific
    employee: "الموظف",
    employeeName: "اسم الموظف",
    designation: "المنصب",
    contractType: "نوع العقد",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    basicSalary: "الراتب الأساسي",
    allowance: "البدل",
    totalSalary: "إجمالي الراتب",
    terms: "الشروط والأحكام",
    
    // Status
    status: "الحالة",
    draft: "مسودة",
    sent: "مرسلة",
    paid: "مدفوعة",
    overdue: "متأخرة",
    pending: "قيد الانتظار",
    approved: "موافق عليه",
    rejected: "مرفوض"
  }
};

// Helper to get translations based on language
export function getPdfTranslations(language = "en") {
  return PDF_TRANSLATIONS[language] || PDF_TRANSLATIONS.en;
}

// Helper to check if language is RTL
export function isRTL(language = "en") {
  return language === "ar";
}

// Helper to get text alignment for language
export function getTextAlign(language = "en") {
  return isRTL(language) ? "right" : "left";
}

// Helper to reverse array for RTL (for table columns)
export function getRTLArray(arr, language = "en") {
  return isRTL(language) ? [...arr].reverse() : arr;
}

